version: "3.2"
services:
    proxy:
        build:
            context: ./proxy
            cache_from:
                - cabinweekend/jitsi-party-proxy:latest
            args:
                - BUILDKIT_INLINE_CACHE=1
        image: cabinweekend/jitsi-party-proxy
        ports:
            - 80:80
            - 443:443
        environment:
            - PROXY_AUTH_ENABLED
            - PROXY_AUTH_DISCOVERY
            - PROXY_AUTH_CLIENT_ID
            - PROXY_AUTH_CLIENT_SECRET
            - PROXY_AUTH_ALLOWED_GROUPS
            - PROXY_NUM_WORKERS=2
        networks:
            party.jitsi:
        depends_on:
            - web-worker_1
            - web-worker_2

    web-worker_1:
        build:
            context: ./app
            cache_from:
                - cabinweekend/jitsi-party-web:latest
            args:
                - BUILDKIT_INLINE_CACHE=1
        image: cabinweekend/jitsi-party-web
        ports:
            - 7071:80
        environment:
            - JITSI_PARTY_DB
            - JITSI_PARTY_DB_USER
            - JITSI_PARTY_DB_PASS
        volumes:
            - ./app:/app
        depends_on:
            - db
            - queue
        networks:
            party.jitsi:

    web-worker_2:
        image: cabinweekend/jitsi-party-web
        ports:
            - 7072:80
        environment:
            - JITSI_PARTY_DB
            - JITSI_PARTY_DB_USER
            - JITSI_PARTY_DB_PASS
        volumes:
            - ./app:/app
        depends_on:
            - db
            - queue
        networks:
            party.jitsi:

    db:
        image: postgres:12.2-alpine
        environment:
            - POSTGRES_USER=${JITSI_PARTY_DB_USER}
            - POSTGRES_PASSWORD=${JITSI_PARTY_DB_PASS}
            - POSTGRES_DB=${JITSI_PARTY_DB}
        ports:
            - 5432:5432
        networks:
            party.jitsi:

    queue:
        image: rabbitmq:3.8.4-management-alpine
        networks:
            party.jitsi:

    jitsi-meet:
        build:
            context: ./meet
            cache_from:
                - cabinweekend/jitsi-party-meet:latest
            args:
                - BUILDKIT_INLINE_CACHE=1
        image: cabinweekend/jitsi-party-meet
        ports:
            - 81:80
        environment:
            - ENABLE_GUESTS
            - DISABLE_HTTPS
            - JICOFO_AUTH_USER
            - XMPP_DOMAIN
            - XMPP_AUTH_DOMAIN
            - XMPP_BOSH_URL_BASE
            - XMPP_GUEST_DOMAIN
            - XMPP_MUC_DOMAIN
            - XMPP_RECORDER_DOMAIN
            - TZ
            - JIBRI_BREWERY_MUC
            - JIBRI_PENDING_TIMEOUT
            - JIBRI_XMPP_USER
            - JIBRI_XMPP_PASSWORD
            - JIBRI_RECORDER_USER
            - JIBRI_RECORDER_PASSWORD
            - BRIDGE_CHANNEL
            - ENABLE_XMPP_WEBSOCKET
        networks:
            party.jitsi:
                aliases:
                    - ${XMPP_DOMAIN}

    prosody:
        build:
            context: ./prosody
            cache_from:
                - cabinweekend/jitsi-party-prosody:latest
                - jitsi/base
            args:
                - BUILDKIT_INLINE_CACHE=1
        image: cabinweekend/jitsi-party-prosody
        environment:
            - ENABLE_GUESTS
            - XMPP_DOMAIN
            - XMPP_AUTH_DOMAIN
            - XMPP_GUEST_DOMAIN
            - XMPP_MUC_DOMAIN
            - XMPP_INTERNAL_MUC_DOMAIN
            - XMPP_MODULES
            - XMPP_MUC_MODULES
            - XMPP_INTERNAL_MUC_MODULES
            - XMPP_RECORDER_DOMAIN
            - JICOFO_COMPONENT_SECRET
            - JICOFO_AUTH_USER
            - JICOFO_AUTH_PASSWORD
            - JVB_AUTH_USER
            - JVB_AUTH_PASSWORD
            - JIGASI_XMPP_USER
            - JIGASI_XMPP_PASSWORD
            - JIBRI_XMPP_USER
            - JIBRI_XMPP_PASSWORD
            - JIBRI_RECORDER_USER
            - JIBRI_RECORDER_PASSWORD
            - TZ
        networks:
            party.jitsi:
                aliases:
                    - ${XMPP_SERVER}

    jicofo:
        image: jitsi/jicofo:stable-5142-4
        environment:
            - XMPP_DOMAIN
            - XMPP_AUTH_DOMAIN
            - XMPP_INTERNAL_MUC_DOMAIN
            - XMPP_SERVER
            - JICOFO_COMPONENT_SECRET
            - JICOFO_AUTH_USER
            - JICOFO_AUTH_PASSWORD
            - JVB_BREWERY_MUC
            - JIGASI_BREWERY_MUC
            - JIBRI_BREWERY_MUC
            - JIBRI_PENDING_TIMEOUT
            - TZ
        depends_on:
            - prosody
        networks:
            party.jitsi:

    jvb:
        image: jitsi/jvb:stable-5142-4
        ports:
            - '${JVB_PORT}:${JVB_PORT}/udp'
            - '${JVB_TCP_PORT}:${JVB_TCP_PORT}'
        environment:
            - XMPP_AUTH_DOMAIN
            - XMPP_INTERNAL_MUC_DOMAIN
            - XMPP_SERVER
            - JVB_AUTH_USER
            - JVB_AUTH_PASSWORD
            - JVB_BREWERY_MUC
            - JVB_PORT
            - JVB_TCP_HARVESTER_DISABLED
            - JVB_TCP_PORT
            - JVB_STUN_SERVERS
            - TZ
        depends_on:
            - prosody
        networks:
            party.jitsi:

    node:
        image: cabinweekend/jitsi-party-node
        build:
            context: .
            cache_from:
                - cabinweekend/jitsi-party-node:latest
            dockerfile: node/Dockerfile
            args:
                - BUILDKIT_INLINE_CACHE=1
        volumes:
            - ./app:/app
            - exclude:/app/client/node_modules

networks:
    party.jitsi:

volumes:
    exclude:
