#!/usr/bin/with-contenv bash

# setting the symlink for key location
rm -rf /config/keys/letsencrypt

if [ -z ${PROXY_LETSENCRYPT_ENABLED+x} ]; then
    mkdir /config/keys/letsencrypt
    cd /config/keys/letsencrypt
    openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 \
        -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=localhost" \
        -keyout privkey.pem -out fullchain.pem

   echo "New self-signed certificate generated; starting openresty"
   exit 0
fi

ln -s /etc/letsencrypt/live/"$PROXY_LETSENCRYPT_DOMAIN" /config/keys/letsencrypt

ACMESERVER="https://acme-v02.api.letsencrypt.org/directory"

# generating certs if necessary
if [ ! -f "/config/keys/letsencrypt/fullchain.pem" ]; then
  echo "Generating new certificate"
  certbot certonly --renew-by-default \
    --server $ACMESERVER \
    --dns-route53 \
    --rsa-key-size 4096 \
    -m cabinweekendparty@gmail.com \
    --no-eff-email \
    --agree-tos \
    -d "*.${PROXY_LETSENCRYPT_DOMAIN}" \
    -d "${PROXY_LETSENCRYPT_DOMAIN}"
  if [ -d /config/keys/letsencrypt ]; then
    cd /config/keys/letsencrypt || exit
  else
    if [ "$VALIDATION" = "dns" ]; then
      echo "ERROR: Cert does not exist! Please see the validation error above. Make sure you entered correct credentials into the /config/dns-conf/${FILENAME} file."
    elif [ "$VALIDATION" = "duckdns" ]; then
      echo "ERROR: Cert does not exist! Please see the validation error above. Make sure your DUCKDNSTOKEN is correct."
    else
      echo "ERROR: Cert does not exist! Please see the validation error above. The issue may be due to incorrect dns or port forwarding settings. Please fix your settings and recreate the container"
    fi
    sleep infinity
  fi
  openssl pkcs12 -export -out privkey.pfx -inkey privkey.pem -in cert.pem -certfile chain.pem -passout pass:
  sleep 1
  cat {privkey,fullchain}.pem > priv-fullchain-bundle.pem
  echo "New certificate generated; starting openresty"
else
  echo "Certificate exists; parameters unchanged; starting openresty"
fi
