#!/usr/bin/with-contenv bash

if [ -z ${PROXY_LETSENCRYPT_ENABLED+x} ]; then
    openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 \
        -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=localhost" \
        -keyout /etc/ssl/private/localhost.key -out /etc/ssl/certs/localhost.crt
    exit 0
fi


# Check if the cert is expired or expires within a day, if so, renew
if openssl x509 -in /config/keys/letsencrypt/fullchain.pem -noout -checkend 86400 >/dev/null; then
    echo "The cert does not expire within the next day. Letting the cron script handle the renewal attempts overnight (2:08am)."
else
    echo "The cert is either expired or it expires within the next day. Attempting to renew. This could take up to 10 minutes."
    /usr/bin/le-renew.sh
    sleep 1
fi
