name: tf-apply

inputs:
  partyConfig:
    description: 'Party config'
    required: true
  partyTheme:
    description: 'Party theme'
    required: true
  vhqEnabled:
    description: 'VHQ enabled'
    required: true
  vhqPlaceholderEnabled:
    description: 'VHQ placeholder enabled'
    required: true
  cognitoAllowedGroups:
    description: 'Allowed Cognito groups'
    required: true

defaults:
  run:
    # explicitly setting `bash` enables safe settings (errexit, pipefail, ...)
    shell: bash

runs:
  using: composite
    runs-on: ubuntu-latest
    steps:
    - name: "Print config"
      run: |
        echo "Config: ${{ github.event.inputs.partyConfig }}"
        echo "Theme: ${{ github.event.inputs.partyTheme }}"
        echo "VHQ Enabled: ${{ github.event.inputs.vhqEnabled }}"
        echo "VHQ Placeholder Enabled: ${{ github.event.inputs.vhqPlaceholderEnabled }}"
        echo "Cognito Allowed Groups: ${{ github.event.inputs.cognitoAllowedGroups }}"

    - name: Terraform apply
      run: |
        cd prod
        terraform init
        terraform apply -auto-approve \
         -var 'vhq_enabled=${{ github.event.inputs.vhqEnabled }}' \
         -var 'vhq_placeholder_enabled=${{ github.event.inputs.vhqPlaceholderEnabled }}' \
         -var 'party_config=${{ github.event.inputs.partyConfig }}' \
         -var 'party_theme=${{ github.event.inputs.partyTheme }}' \
         -var 'cognito_allowed_groups=${{ github.event.inputs.cognitoAllowedGroups }}' \

