name: wait-for-house

inputs:
  tries:
    description: 'Number of tries'
    default: 60
  interval:
    description: 'Interval (seconds)'
    default: 5

runs:
  using: composite
  steps:
  - name: "Print config"
    shell: bash
    run: |
      echo "Tries: ${{ inputs.tries }}"
      echo "Interval: ${{ inputs.interval }}"

  - name: Check house
    shell: bash {0}
    run: |
      i=0
      ret=1
      while [ $i -lt ${{ inputs.tries }} ] && [ ! ${ret} -eq 0 ]; do
        sleep ${{ inputs.interval }}
        echo "Checking..."
        curl -s https://testing.enter.thesatanic.estate/ > /dev/null
        ret=$?
        let i++
      done
