name: build-push

on:
  push:
    branches:
      - master

defaults:
  run:
    # explicitly setting `bash` enables safe settings (errexit, pipefail, ...)
    shell: bash

jobs:
  build-test-push:
    runs-on: ubuntu-20.04
    outputs:
      tag: ${{ steps.prep.outputs.tag }}

    strategy:
      matrix:
        config: [base, temple, factionhall, tstvhq, gojo-video]
        include:
          - config: base
            theme: basic

          - config: temple
            theme: temple

          - config: factionhall
            theme: factionhall

          - config: tstvhq
            theme: hexennacht

          - config: gojo-video
            theme: basic

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.0
      with:
        access_token: ${{ github.token }}
    
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Detect changed files
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          app:
            - 'app/**'

    - name: Prep tags
      id: prep
      run: |
        IMAGE=cabinweekend/jitsi-party-web
        TAG_SHA=${{ matrix.config }}-${{ matrix.theme }}-$(echo $GITHUB_SHA)
        TAG_LATEST=${{ matrix.config }}-${{ matrix.theme }}-latest
        echo ::set-output name=tagged_image_sha::${IMAGE}:${TAG_SHA}
        echo ::set-output name=tagged_image_latest::${IMAGE}:${TAG_LATEST}

    - name: Set config and theme
      run:
        app/set_config.sh ${{ matrix.config }}
        app/set_theme.sh ${{ matrix.theme }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        install: true # Aliases docker build command to docker buildx

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and tag app image
      if: ${{ steps.changes.outputs.app }} == 'true'
      uses: docker/build-push-action@v2
      with:
        context: ./app
        builder: ${{ steps.buildx.outputs.name }}
        file: ./app/Dockerfile
        push: true
        tags: ${{ steps.prep.outputs.tagged_image_sha }},${{ steps.prep.outputs.tagged_image_latest }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
