name: delay-until-time
on:
  workflow_dispatch:
    inputs:
      targetTime:
        description: 'Target time'
        type: string
        required: true
        default: '00:00:15'
jobs:
  doTheRestOfTheWork:
    runs-on: ubuntu-latest
    environment: delay15Minutes
    steps:
      - name: Check clock
        id: checkClock
        uses: cardinalby/js-eval-action@v1
        env:
          targetTime: ${{ github.event.inputs.targetTime }}
        with:
          expression: |
            {
              const
                targetTime = parseInt(env.targetTime),
              assert(targetTime == now);
              return true;
            }

      ## Call itself again
      - uses: benc-uk/workflow-dispatch@v1
        if: |
          steps.checkClock.outcome != 'success'
        with:
          workflow: ${{ github.workflow }}
          token: ${{ secrets.PERSONAL_TOKEN }}
          inputs: |
            {
              "targetTime": "${{github.event.inputs.targetTime}}"
            }
