name: shutdown

on:
  workflow_dispatch:

defaults:
  run:
    # explicitly setting `bash` enables safe settings (errexit, pipefail, ...)
    shell: bash

jobs:
  shutdown:
    runs-on: ubuntu-latest
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.0
      with:
        access_token: ${{ github.token }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Shut down house
      uses: ./.github/actions/tf-apply
      with:
        vhqEnabled: false
        partyConfig: dummy
        partyTheme: dummy
        vhqPlaceholderEnabled: true
        cognitoAllowedGroups: dummy
